import React from 'react';
import './Event.css';
export default class Event extends React.Component {
  render() {
    let props = this.props;

    return (
// Phasellus ac accumsan enim. Maecenas porttitor risus in tortor molestie imperdiet. Fusce eu tortor mattis urna lobortis lobortis vel non leo. Proin egestas dui ut augue consectetur molestie. Nunc vitae dictum ante, id iaculis eros. Curabitur ante nisl, posuere eget lectus a, sodales mattis odio. Sed blandit consectetur convallis. Etiam id volutpat leo, id iaculis velit. Aliquam scelerisque at nisl ut porttitor. Integer facilisis cursus est, sed pharetra nibh consectetur ac. Curabitur dui elit, finibus non massa vitae, dictum hendrerit dolor. Suspendisse potenti. Quisque dignissim tristique lacus ut bibendum. Pellentesque sapien mauris, ultrices ut ultrices non, feugiat et sapien. Phasellus bibendum justo diam, vitae scelerisque justo luctus nec.
// Phasellus ac accumsan enim. Maecenas porttitor risus in tortor molestie imperdiet. Fusce eu tortor mattis urna lobortis lobortis vel non leo. Proin egestas dui ut augue consectetur molestie. Nunc vitae dictum ante, id iaculis eros. Curabitur ante nisl, posuere eget lectus a, sodales mattis odio. Sed blandit consectetur convallis. Etiam id volutpat leo, id iaculis velit. Aliquam scelerisque at nisl ut porttitor. Integer facilisis cursus est, sed pharetra nibh consectetur ac. Curabitur dui elit, finibus non massa vitae, dictum hendrerit dolor. Suspendisse potenti. Quisque dignissim tristique lacus ut bibendum. Pellentesque sapien mauris, ultrices ut ultrices non, feugiat et sapien. Phasellus bibendum justo diam, vitae scelerisque justo luctus nec.
// Phasellus ac accumsan enim. Maecenas porttitor risus in tortor molestie imperdiet. Fusce eu tortor mattis urna lobortis lobortis vel non leo. Proin egestas dui ut augue consectetur molestie. Nunc vitae dictum ante, id iaculis eros. Curabitur ante nisl, posuere eget lectus a, sodales mattis odio. Sed blandit consectetur convallis. Etiam id volutpat leo, id iaculis velit. Aliquam scelerisque at nisl ut porttitor. Integer facilisis cursus est, sed pharetra nibh consectetur ac. Curabitur dui elit, finibus non massa vitae, dictum hendrerit dolor. Suspendisse potenti. Quisque dignissim tristique lacus ut bibendum. Pellentesque sapien mauris, ultrices ut ultrices non, feugiat et sapien. Phasellus bibendum justo diam, vitae scelerisque justo luctus nec.
// Phasellus ac accumsan enim. Maecenas porttitor risus in tortor molestie imperdiet. Fusce eu tortor mattis urna lobortis lobortis vel non leo. Proin egestas dui ut augue consectetur molestie. Nunc vitae dictum ante, id iaculis eros. Curabitur ante nisl, posuere eget lectus a, sodales mattis odio. Sed blandit consectetur convallis. Etiam id volutpat leo, id iaculis velit. Aliquam scelerisque at nisl ut porttitor. Integer facilisis cursus est, sed pharetra nibh consectetur ac. Curabitur dui elit, finibus non massa vitae, dictum hendrerit dolor. Suspendisse potenti. Quisque dignissim tristique lacus ut bibendum. Pellentesque sapien mauris, ultrices ut ultrices non, feugiat et sapien. Phasellus bibendum justo diam, vitae scelerisque justo luctus nec.
// Phasellus ac accumsan enim. Maecenas porttitor risus in tortor molestie imperdiet. Fusce eu tortor mattis urna lobortis lobortis vel non leo. Proin egestas dui ut augue consectetur molestie. Nunc vitae dictum ante, id iaculis eros. Curabitur ante nisl, posuere eget lectus a, sodales mattis odio. Sed blandit consectetur convallis. Etiam id volutpat leo, id iaculis velit. Aliquam scelerisque at nisl ut porttitor. Integer facilisis cursus est, sed pharetra nibh consectetur ac. Curabitur dui elit, finibus non massa vitae, dictum hendrerit dolor. Suspendisse potenti. Quisque dignissim tristique lacus ut bibendum. Pellentesque sapien mauris, ultrices ut ultrices non, feugiat et sapien. Phasellus bibendum justo diam, vitae scelerisque justo luctus nec.
// Phasellus ac accumsan enim. Maecenas porttitor risus in tortor molestie imperdiet. Fusce eu tortor mattis urna lobortis lobortis vel non leo. Proin egestas dui ut augue consectetur molestie. Nunc vitae dictum ante, id iaculis eros. Curabitur ante nisl, posuere eget lectus a, sodales mattis odio. Sed blandit consectetur convallis. Etiam id volutpat leo, id iaculis velit. Aliquam scelerisque at nisl ut porttitor. Integer facilisis cursus est, sed pharetra nibh consectetur ac. Curabitur dui elit, finibus non massa vitae, dictum hendrerit dolor. Suspendisse potenti. Quisque dignissim tristique lacus ut bibendum. Pellentesque sapien mauris, ultrices ut ultrices non, feugiat et sapien. Phasellus bibendum justo diam, vitae scelerisque justo luctus nec.
// Phasellus ac accumsan enim. Maecenas porttitor risus in tortor molestie imperdiet. Fusce eu tortor mattis urna lobortis lobortis vel non leo. Proin egestas dui ut augue consectetur molestie. Nunc vitae dictum ante, id iaculis eros. Curabitur ante nisl, posuere eget lectus a, sodales mattis odio. Sed blandit consectetur convallis. Etiam id volutpat leo, id iaculis velit. Aliquam scelerisque at nisl ut porttitor. Integer facilisis cursus est, sed pharetra nibh consectetur ac. Curabitur dui elit, finibus non massa vitae, dictum hendrerit dolor. Suspendisse potenti. Quisque dignissim tristique lacus ut bibendum. Pellentesque sapien mauris, ultrices ut ultrices non, feugiat et sapien. Phasellus bibendum justo diam, vitae scelerisque justo luctus nec.
// Phasellus ac accumsan enim. Maecenas porttitor risus in tortor molestie imperdiet. Fusce eu tortor mattis urna lobortis lobortis vel non leo. Proin egestas dui ut augue consectetur molestie. Nunc vitae dictum ante, id iaculis eros. Curabitur ante nisl, posuere eget lectus a, sodales mattis odio. Sed blandit consectetur convallis. Etiam id volutpat leo, id iaculis velit. Aliquam scelerisque at nisl ut porttitor. Integer facilisis cursus est, sed pharetra nibh consectetur ac. Curabitur dui elit, finibus non massa vitae, dictum hendrerit dolor. Suspendisse potenti. Quisque dignissim tristique lacus ut bibendum. Pellentesque sapien mauris, ultrices ut ultrices non, feugiat et sapien. Phasellus bibendum justo diam, vitae scelerisque justo luctus nec.
// Phasellus ac accumsan enim. Maecenas porttitor risus in tortor molestie imperdiet. Fusce eu tortor mattis urna lobortis lobortis vel non leo. Proin egestas dui ut augue consectetur molestie. Nunc vitae dictum ante, id iaculis eros. Curabitur ante nisl, posuere eget lectus a, sodales mattis odio. Sed blandit consectetur convallis. Etiam id volutpat leo, id iaculis velit. Aliquam scelerisque at nisl ut porttitor. Integer facilisis cursus est, sed pharetra nibh consectetur ac. Curabitur dui elit, finibus non massa vitae, dictum hendrerit dolor. Suspendisse potenti. Quisque dignissim tristique lacus ut bibendum. Pellentesque sapien mauris, ultrices ut ultrices non, feugiat et sapien. Phasellus bibendum justo diam, vitae scelerisque justo luctus nec.
// Phasellus ac accumsan enim. Maecenas porttitor risus in tortor molestie imperdiet. Fusce eu tortor mattis urna lobortis lobortis vel non leo. Proin egestas dui ut augue consectetur molestie. Nunc vitae dictum ante, id iaculis eros. Curabitur ante nisl, posuere eget lectus a, sodales mattis odio. Sed blandit consectetur convallis. Etiam id volutpat leo, id iaculis velit. Aliquam scelerisque at nisl ut porttitor. Integer facilisis cursus est, sed pharetra nibh consectetur ac. Curabitur dui elit, finibus non massa vitae, dictum hendrerit dolor. Suspendisse potenti. Quisque dignissim tristique lacus ut bibendum. Pellentesque sapien mauris, ultrices ut ultrices non, feugiat et sapien. Phasellus bibendum justo diam, vitae scelerisque justo luctus nec.
// Phasellus ac accumsan enim. Maecenas porttitor risus in tortor molestie imperdiet. Fusce eu tortor mattis urna lobortis lobortis vel non leo. Proin egestas dui ut augue consectetur molestie. Nunc vitae dictum ante, id iaculis eros. Curabitur ante nisl, posuere eget lectus a, sodales mattis odio. Sed blandit consectetur convallis. Etiam id volutpat leo, id iaculis velit. Aliquam scelerisque at nisl ut porttitor. Integer facilisis cursus est, sed pharetra nibh consectetur ac. Curabitur dui elit, finibus non massa vitae, dictum hendrerit dolor. Suspendisse potenti. Quisque dignissim tristique lacus ut bibendum. Pellentesque sapien mauris, ultrices ut ultrices non, feugiat et sapien. Phasellus bibendum justo diam, vitae scelerisque justo luctus nec.
// Phasellus ac accumsan enim. Maecenas porttitor risus in tortor molestie imperdiet. Fusce eu tortor mattis urna lobortis lobortis vel non leo. Proin egestas dui ut augue consectetur molestie. Nunc vitae dictum ante, id iaculis eros. Curabitur ante nisl, posuere eget lectus a, sodales mattis odio. Sed blandit consectetur convallis. Etiam id volutpat leo, id iaculis velit. Aliquam scelerisque at nisl ut porttitor. Integer facilisis cursus est, sed pharetra nibh consectetur ac. Curabitur dui elit, finibus non massa vitae, dictum hendrerit dolor. Suspendisse potenti. Quisque dignissim tristique lacus ut bibendum. Pellentesque sapien mauris, ultrices ut ultrices non, feugiat et sapien. Phasellus bibendum justo diam, vitae scelerisque justo luctus nec.
// Phasellus ac accumsan enim. Maecenas porttitor risus in tortor molestie imperdiet. Fusce eu tortor mattis urna lobortis lobortis vel non leo. Proin egestas dui ut augue consectetur molestie. Nunc vitae dictum ante, id iaculis eros. Curabitur ante nisl, posuere eget lectus a, sodales mattis odio. Sed blandit consectetur convallis. Etiam id volutpat leo, id iaculis velit. Aliquam scelerisque at nisl ut porttitor. Integer facilisis cursus est, sed pharetra nibh consectetur ac. Curabitur dui elit, finibus non massa vitae, dictum hendrerit dolor. Suspendisse potenti. Quisque dignissim tristique lacus ut bibendum. Pellentesque sapien mauris, ultrices ut ultrices non, feugiat et sapien. Phasellus bibendum justo diam, vitae scelerisque justo luctus nec.
// Phasellus ac accumsan enim. Maecenas porttitor risus in tortor molestie imperdiet. Fusce eu tortor mattis urna lobortis lobortis vel non leo. Proin egestas dui ut augue consectetur molestie. Nunc vitae dictum ante, id iaculis eros. Curabitur ante nisl, posuere eget lectus a, sodales mattis odio. Sed blandit consectetur convallis. Etiam id volutpat leo, id iaculis velit. Aliquam scelerisque at nisl ut porttitor. Integer facilisis cursus est, sed pharetra nibh consectetur ac. Curabitur dui elit, finibus non massa vitae, dictum hendrerit dolor. Suspendisse potenti. Quisque dignissim tristique lacus ut bibendum. Pellentesque sapien mauris, ultrices ut ultrices non, feugiat et sapien. Phasellus bibendum justo diam, vitae scelerisque justo luctus nec.
// Phasellus ac accumsan enim. Maecenas porttitor risus in tortor molestie imperdiet. Fusce eu tortor mattis urna lobortis lobortis vel non leo. Proin egestas dui ut augue consectetur molestie. Nunc vitae dictum ante, id iaculis eros. Curabitur ante nisl, posuere eget lectus a, sodales mattis odio. Sed blandit consectetur convallis. Etiam id volutpat leo, id iaculis velit. Aliquam scelerisque at nisl ut porttitor. Integer facilisis cursus est, sed pharetra nibh consectetur ac. Curabitur dui elit, finibus non massa vitae, dictum hendrerit dolor. Suspendisse potenti. Quisque dignissim tristique lacus ut bibendum. Pellentesque sapien mauris, ultrices ut ultrices non, feugiat et sapien. Phasellus bibendum justo diam, vitae scelerisque justo luctus nec.
// Phasellus ac accumsan enim. Maecenas porttitor risus in tortor molestie imperdiet. Fusce eu tortor mattis urna lobortis lobortis vel non leo. Proin egestas dui ut augue consectetur molestie. Nunc vitae dictum ante, id iaculis eros. Curabitur ante nisl, posuere eget lectus a, sodales mattis odio. Sed blandit consectetur convallis. Etiam id volutpat leo, id iaculis velit. Aliquam scelerisque at nisl ut porttitor. Integer facilisis cursus est, sed pharetra nibh consectetur ac. Curabitur dui elit, finibus non massa vitae, dictum hendrerit dolor. Suspendisse potenti. Quisque dignissim tristique lacus ut bibendum. Pellentesque sapien mauris, ultrices ut ultrices non, feugiat et sapien. Phasellus bibendum justo diam, vitae scelerisque justo luctus nec.
// Phasellus ac accumsan enim. Maecenas porttitor risus in tortor molestie imperdiet. Fusce eu tortor mattis urna lobortis lobortis vel non leo. Proin egestas dui ut augue consectetur molestie. Nunc vitae dictum ante, id iaculis eros. Curabitur ante nisl, posuere eget lectus a, sodales mattis odio. Sed blandit consectetur convallis. Etiam id volutpat leo, id iaculis velit. Aliquam scelerisque at nisl ut porttitor. Integer facilisis cursus est, sed pharetra nibh consectetur ac. Curabitur dui elit, finibus non massa vitae, dictum hendrerit dolor. Suspendisse potenti. Quisque dignissim tristique lacus ut bibendum. Pellentesque sapien mauris, ultrices ut ultrices non, feugiat et sapien. Phasellus bibendum justo diam, vitae scelerisque justo luctus nec.
// Phasellus ac accumsan enim. Maecenas porttitor risus in tortor molestie imperdiet. Fusce eu tortor mattis urna lobortis lobortis vel non leo. Proin egestas dui ut augue consectetur molestie. Nunc vitae dictum ante, id iaculis eros. Curabitur ante nisl, posuere eget lectus a, sodales mattis odio. Sed blandit consectetur convallis. Etiam id volutpat leo, id iaculis velit. Aliquam scelerisque at nisl ut porttitor. Integer facilisis cursus est, sed pharetra nibh consectetur ac. Curabitur dui elit, finibus non massa vitae, dictum hendrerit dolor. Suspendisse potenti. Quisque dignissim tristique lacus ut bibendum. Pellentesque sapien mauris, ultrices ut ultrices non, feugiat et sapien. Phasellus bibendum justo diam, vitae scelerisque justo luctus nec.
// Phasellus ac accumsan enim. Maecenas porttitor risus in tortor molestie imperdiet. Fusce eu tortor mattis urna lobortis lobortis vel non leo. Proin egestas dui ut augue consectetur molestie. Nunc vitae dictum ante, id iaculis eros. Curabitur ante nisl, posuere eget lectus a, sodales mattis odio. Sed blandit consectetur convallis. Etiam id volutpat leo, id iaculis velit. Aliquam scelerisque at nisl ut porttitor. Integer facilisis cursus est, sed pharetra nibh consectetur ac. Curabitur dui elit, finibus non massa vitae, dictum hendrerit dolor. Suspendisse potenti. Quisque dignissim tristique lacus ut bibendum. Pellentesque sapien mauris, ultrices ut ultrices non, feugiat et sapien. Phasellus bibendum justo diam, vitae scelerisque justo luctus nec.
// Phasellus ac accumsan enim. Maecenas porttitor risus in tortor molestie imperdiet. Fusce eu tortor mattis urna lobortis lobortis vel non leo. Proin egestas dui ut augue consectetur molestie. Nunc vitae dictum ante, id iaculis eros. Curabitur ante nisl, posuere eget lectus a, sodales mattis odio. Sed blandit consectetur convallis. Etiam id volutpat leo, id iaculis velit. Aliquam scelerisque at nisl ut porttitor. Integer facilisis cursus est, sed pharetra nibh consectetur ac. Curabitur dui elit, finibus non massa vitae, dictum hendrerit dolor. Suspendisse potenti. Quisque dignissim tristique lacus ut bibendum. Pellentesque sapien mauris, ultrices ut ultrices non, feugiat et sapien. Phasellus bibendum justo diam, vitae scelerisque justo luctus nec.
// Phasellus ac accumsan enim. Maecenas porttitor risus in tortor molestie imperdiet. Fusce eu tortor mattis urna lobortis lobortis vel non leo. Proin egestas dui ut augue consectetur molestie. Nunc vitae dictum ante, id iaculis eros. Curabitur ante nisl, posuere eget lectus a, sodales mattis odio. Sed blandit consectetur convallis. Etiam id volutpat leo, id iaculis velit. Aliquam scelerisque at nisl ut porttitor. Integer facilisis cursus est, sed pharetra nibh consectetur ac. Curabitur dui elit, finibus non massa vitae, dictum hendrerit dolor. Suspendisse potenti. Quisque dignissim tristique lacus ut bibendum. Pellentesque sapien mauris, ultrices ut ultrices non, feugiat et sapien. Phasellus bibendum justo diam, vitae scelerisque justo luctus nec.
// Phasellus ac accumsan enim. Maecenas porttitor risus in tortor molestie imperdiet. Fusce eu tortor mattis urna lobortis lobortis vel non leo. Proin egestas dui ut augue consectetur molestie. Nunc vitae dictum ante, id iaculis eros. Curabitur ante nisl, posuere eget lectus a, sodales mattis odio. Sed blandit consectetur convallis. Etiam id volutpat leo, id iaculis velit. Aliquam scelerisque at nisl ut porttitor. Integer facilisis cursus est, sed pharetra nibh consectetur ac. Curabitur dui elit, finibus non massa vitae, dictum hendrerit dolor. Suspendisse potenti. Quisque dignissim tristique lacus ut bibendum. Pellentesque sapien mauris, ultrices ut ultrices non, feugiat et sapien. Phasellus bibendum justo diam, vitae scelerisque justo luctus nec.
// Phasellus ac accumsan enim. Maecenas porttitor risus in tortor molestie imperdiet. Fusce eu tortor mattis urna lobortis lobortis vel non leo. Proin egestas dui ut augue consectetur molestie. Nunc vitae dictum ante, id iaculis eros. Curabitur ante nisl, posuere eget lectus a, sodales mattis odio. Sed blandit consectetur convallis. Etiam id volutpat leo, id iaculis velit. Aliquam scelerisque at nisl ut porttitor. Integer facilisis cursus est, sed pharetra nibh consectetur ac. Curabitur dui elit, finibus non massa vitae, dictum hendrerit dolor. Suspendisse potenti. Quisque dignissim tristique lacus ut bibendum. Pellentesque sapien mauris, ultrices ut ultrices non, feugiat et sapien. Phasellus bibendum justo diam, vitae scelerisque justo luctus nec.
// Phasellus ac accumsan enim. Maecenas porttitor risus in tortor molestie imperdiet. Fusce eu tortor mattis urna lobortis lobortis vel non leo. Proin egestas dui ut augue consectetur molestie. Nunc vitae dictum ante, id iaculis eros. Curabitur ante nisl, posuere eget lectus a, sodales mattis odio. Sed blandit consectetur convallis. Etiam id volutpat leo, id iaculis velit. Aliquam scelerisque at nisl ut porttitor. Integer facilisis cursus est, sed pharetra nibh consectetur ac. Curabitur dui elit, finibus non massa vitae, dictum hendrerit dolor. Suspendisse potenti. Quisque dignissim tristique lacus ut bibendum. Pellentesque sapien mauris, ultrices ut ultrices non, feugiat et sapien. Phasellus bibendum justo diam, vitae scelerisque justo luctus nec.
// Phasellus ac accumsan enim. Maecenas porttitor risus in tortor molestie imperdiet. Fusce eu tortor mattis urna lobortis lobortis vel non leo. Proin egestas dui ut augue consectetur molestie. Nunc vitae dictum ante, id iaculis eros. Curabitur ante nisl, posuere eget lectus a, sodales mattis odio. Sed blandit consectetur convallis. Etiam id volutpat leo, id iaculis velit. Aliquam scelerisque at nisl ut porttitor. Integer facilisis cursus est, sed pharetra nibh consectetur ac. Curabitur dui elit, finibus non massa vitae, dictum hendrerit dolor. Suspendisse potenti. Quisque dignissim tristique lacus ut bibendum. Pellentesque sapien mauris, ultrices ut ultrices non, feugiat et sapien. Phasellus bibendum justo diam, vitae scelerisque justo luctus nec.


      <div className="event" key={props.key}>
        <div className="event__header">
          <span className="event__date">
            <p>{props.date} </p>
          </span>
          <img className="event__avatar" alt={props.name} src={props.avatar ? props.avatar.photo_link : 'https://www.zndrke.com/dashboard/img/placeholder.png'} />
        </div>
        <div className="event__info" >
          <span className="event__place">
            <p>{props.place} | {props.address} </p>
          </span>
          <span className="event__name">
            <h2>{props.name}</h2>
          </span>
          <span className="event__time">
            <p>{props.time}</p>
          </span>
        </div>
        <div className="event__description">
          <p> {props.description}</p>
        </div>
      </div>
    )
  }
}